### ISSUE TITLE
rehype-minify-whitespace: inline HTML content is trimmed

### ISSUE THREAD

**Issue by erquhart** [rehypejs/rehype-minify#19]
The contents of inline tags are being trimmed. When parsing html to markdown:

**Input**
```
a b<span> </span>c d</span><strong> e</strong>
```

**Expected output**
```
a b c d **e**
```

**Actual output**
```
a bc d**e**
```

Runkit repro: https://runkit.com/erquhart/595d36c4e60f6b0012c00405

**Comment by wooorm** [comment]
If someone wants to work on it, it’s in [`rehype-minify-whitespace`](https://github.com/wooorm/rehype-minify/tree/master/packages/rehype-minify-whitespace).

Moved from https://github.com/wooorm/remark/issues/275.

**Comment by erquhart** [comment]
Ah, wrong repo, sorry! I'll move it again lol.

**Comment by erquhart** [comment]
@wooorm I'm not using rehype-minify-whitespace in that repro - are you certain that's the problem?

**Comment by wooorm** [comment]
[Yup](https://github.com/syntax-tree/hast-util-to-mdast/blob/f350a40659bde6b4a68d3f2f5cd0c844a2dbe07a/index.js#L5)

**Comment by erquhart** [comment]
@wooorm seems like the best approach may be to simply allow minification to be toggled off in the options for rehype-remark/hast-util-to-mdast. Would you accept a PR for that?

**Comment by wooorm** [comment]
Just dropping this here ’cause it probably has to be something like this: https://github.com/wooorm/remark-lint/blob/master/packages/remark-lint-no-paragraph-content-indent/index.js

**Comment by erezrokah** [comment]
Bumping this as we're still experiencing this issue: https://github.com/netlify/netlify-cms/issues/3727

I added a test that is failing https://github.com/erezrokah/rehype-minify/commit/d7cc409c35e9d91c4f0d569f107e1122d3edb082#diff-c7e2175747a03e137c1615aecfaa1636R103 but not sure how to go about fixing it.

Can you suggest a place to get started?
Tried looking at the history of https://github.com/wooorm/remark-lint/blob/master/packages/remark-lint-no-paragraph-content-indent/index.js but couldn't figure out the suggested direction.

**Comment by kptdobe** [comment]
I am facing the same issue. It is coming from those lines: 

https://github.com/rehypejs/rehype-minify/blob/master/packages/rehype-minify-whitespace/index.js#L62-L68

I think the problem is that in the case of a `<span>`, `<em>`, `<strong>`, the siblings you want to test are not the node siblings (almost always non existing) but the siblings of the parent.

**Comment by kptdobe** [comment]
Re-thinking about it, I would even argue you should never trim an inline element: there is no way you can know if the leading / trailing space has been introduced on purpose or not:
- `<span>Click here: </span><input text="my button" value="button">`
- `<p><strong> Maybe I want to start with a space here...</strong></p>`

**Comment by wooorm** [comment]
Released!

**Comment by erezrokah** [comment]
This is amazing @wooorm, do you suggest I open PRs for https://github.com/syntax-tree/hast-util-to-mdast/blob/7c4667743dd056b33f1c76a7c319674aef951a4f/package.json#L40 and https://github.com/rehypejs/rehype-remark/blob/10c28f586be34b1baf3d221d8116a7e70aed2365/package.json#L28 to update dependencies?
Would a major version bump will be required for those?

**Comment by wooorm** [comment]
It's a patch, so reinstalling dependencies should do the trick!

**Comment by erezrokah** [comment]
Sorry, let me clarify my question.
We're using `rehype-remark`. Even if I update it to the latest version is still uses `"hast-util-to-mdast": "^7.0.0"` which uses `"rehype-minify-whitespace": "^3.0.0"`, so it won't get the fix.

I'm using (with `yarn`) the following workaround:
```json
"resolutions": {
  "rehype-minify-whitespace": "^4.0.2"
}
```
But that is not ideal

**Comment by kptdobe** [comment]
Awesome! Thanks a lot @wooorm.

I tried to test the changes (I manually patched "rehype-remark") and I get an error:

```
TypeError: Cannot read property 'type' of undefined
    at one .../hast-util-to-mdast/lib/one.js:13:12)
```

I traced to https://github.com/syntax-tree/hast-util-to-mdast/blob/master/index.js#L31 : `minify ` returns undefined for my tree (was working before). Investigating too :)

**Comment by kptdobe** [comment]
@wooorm You removed the `return tree` :)

https://github.com/rehypejs/rehype-minify/commit/64c6206f2ac5c25a4465966a6e29ac696ed63f8b#diff-a6b748a472d9e6a0024e05443221d898L44

Adding here fix the issue: https://github.com/rehypejs/rehype-minify/blob/master/packages/rehype-minify-whitespace/index.js#L40

**Comment by kptdobe** [comment]
Created a PR to address this new issue: https://github.com/rehypejs/rehype-minify/pull/33
Feel free to use it or not ;)

I tested the new trimming behaviors, works pretty well, especially with "my" complex DOM. Thanks again!
