### ISSUE TITLE
Collapse whitespace more safely

### ISSUE THREAD

**Issue by stevenvachon** [rehypejs/rehype-minify#27]
... with [normalize-html-whitespace](https://npmjs.com/normalize-html-whitespace) instead of [collapse-white-space](https://npmjs.com/collapse-white-space).

**Comment by ChristianMurphy** [comment]
Nice!
@stevenvachon have you run into an edge case that you could share where `collapse-white-space` caused an issue?
I'm also mildly concerned with replacing a [SemVer stable](https://semver.org/#spec-item-5) library (`collapse-white-space` is at version 1.0.4) with a library that is [SemVer unstable](https://semver.org/#spec-item-4) (`normalize-html-whitespace` is at version 0.2.0). Is there a stable release planned?

**Comment by stevenvachon** [comment]
I haven't yet used this library, but will be deciding between it, reshape and posthtml in the future. I'd just like for them all to benefit from my work. There're no plans for a 1.x, but there're also no plans for breaking changes. Perhaps a 1.x is due after such a long wait (for bug reports) in 0.x

**Comment by wooorm** [comment]
@stevenvachon Interesting aside: the timestamps are weird btw! Something up with your computer? <img width="261" alt="screenshot 2019-02-25 at 9 13 30 am" src="https://user-images.githubusercontent.com/944406/53355332-a0e80980-38dd-11e9-91c4-bfaa3859be3a.png">

> I haven't yet used this library, but will be deciding between it, reshape and posthtml in the future. I'd just like for them all to benefit from my work

Alright. Well, I’m up for using your project over collapse-white-space, but I’d appreciate a PR with tests !

**Comment by stevenvachon** [comment]
> the timestamps are weird btw! Something up with your computer?

Force-pushes will do that.

> I’d appreciate a PR with tests

I'll see what I can do.

**Comment by wooorm** [comment]
Feel free to ping back here when you can, we’d appreciate the tests. But for now I’m closing this.

**Comment by stevenvachon** [comment]
So, it's not important to have correct logic unless you don't have to do it yourself?

**Comment by wooorm** [comment]
> So, it's not important to have correct logic unless you don't have to do it yourself?

I think it’s important that you understand that I’ve spent a lot of time already on these projects and that the version you get is my gift to you.
It’s just that changes should come with a test.
You can read more about the rights you have in the [license](https://github.com/rehypejs/rehype-minify/blob/master/license).

**Comment by stevenvachon** [comment]
I have no rights. I questioned your dedication to quality.
