### ISSUE TITLE
Add more "missing value defaults"

### ISSUE THREAD

**Issue by karlhorky** [rehypejs/rehype-minify#36]
Hi @wooorm! 

### Subject of the feature

As discussed, [the `rehype-minify-enumerated-attribute` schema](https://github.com/rehypejs/rehype-minify/blob/668ddd79d6a734bd8f0101ff237338c599d15554/packages/rehype-minify-enumerated-attribute/schema.js) doesn't include some ["missing value defaults"](https://html.spec.whatwg.org/multipage/common-microsyntaxes.html#missing-value-default):

- `img[loading]`
- `iframe[loading]`
- `form[target]`
- `button[formtarget]`
- `ol[type]`
- `li[type]`
- `ul[type]` (although, this is deprecated)

These are just the ones that I have found in my short, spotty research on MDN. There are probably more.

### Problem

I'm trying to gather a list of "missing value defaults" for a new ESLint rule:

https://github.com/yannickcr/eslint-plugin-react/issues/2866

### Expected behavior

The list should be complete.

### Alternatives

Use another library, such as one from the list below:

- [`html-minifier`](https://github.com/kangax/html-minifier/blob/583e0861ee852a76acb1e8ec00b3de35a024927d/src/htmlminifier.js#L125-L153)
- [`htmlnano`](https://github.com/posthtml/htmlnano/blob/c40c99b7477885f0e02b8eb733907a8dee870ea2/lib/modules/removeRedundantAttributes.es6#L21-L90)

**Comment by wooorm** [comment]
`target` can’t work, because it’s not an enumerated attribute. It can have other values: https://html.spec.whatwg.org/multipage/browsers.html#valid-browsing-context-name-or-keyword

**Comment by karlhorky** [comment]
Oh, oops... is there another package that would handle this?

Or, if it will be extracted to a new package à la #37 , maybe this would be a good addition to the new data package?

**Comment by wooorm** [comment]
`ol[type]` is not defined as enumerated, but seems to be, so I think I can add that.
`ul[type]` and `li[type]` are deprecated, so I can add them here, but for a linter you should probably warn about their use.

`loading` is a new enumerated attribute and I’ll add them

**Comment by wooorm** [comment]
> is there another package that would handle this?

It can have any string (so long as it doesn‘t start with a `_`), so I don’t think it can be handled? 🤷‍♂️

**Comment by wooorm** [comment]
Released! Thanks!

**Comment by karlhorky** [comment]
> `target` can’t work, because it’s not an enumerated attribute

So looking at [the MDN page](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/form#attr-target), it seems like `target` has some "enumerated-like" values (which have special meanings):

- `_self` (default if missing)
- `_blank`
- `_parent`
- `_top`

> I don’t think it can be handled?

So maybe these above could be handled (including the default value if it's missing)?

If you want to separate between "strictly enumerated" and other types, then the object shape for an attribute could have an extra field (eg. `type: "enumerated"`). This would allow for handling missing value defaults of non-enumerated attributes.

**Comment by karlhorky** [comment]
And thanks for the addition + release!

**Comment by wooorm** [comment]
So, for eslint-plugin-react, the thing is that you want to drop `_self` if it is specified, right?

**Comment by karlhorky** [comment]
> So, for eslint-plugin-react, the thing is that you want to drop `_self` if it is specified, right?

Right, as in the issue:

```jsx
// Incorrect
<form target="_self"></form>

// Correct
<form></form>
```

**Comment by wooorm** [comment]
Alright, so implementing that here makes sense too. It’d mean that “invalid” values are allowed ([instead of translated to a different invalid value](https://github.com/rehypejs/rehype-minify/blob/3e1903a2bbc4c5a9d56812ca2d050fe4f36b84c4/packages/rehype-minify-enumerated-attribute/index.js#L101)).
And for the schema, maybe a key `allowUnknownStates`?

**Comment by karlhorky** [comment]
> It’d mean that “invalid” values are allowed

Do you mean because attributes like `target` can also have values not in the `states` array? If I'm understanding correctly, then yes.

> And for the schema, maybe a key `allowUnknownStates`?

Right, given the rest of the nomenclature in the package, that would seem to make sense.

**Comment by wooorm** [comment]
alright, fixed!

**Comment by karlhorky** [comment]
Should the `missing` value for `ol[type]` be `'1'`? Seems that way on MDN at least...

**Comment by karlhorky** [comment]
Oh and `form[target]` - should this be `'_self'`?

**Comment by karlhorky** [comment]
Going through MDN and the HTML spec, found some more inconsistencies / additions:

1. `[autocomplete]`: should this have an array of `tagNames`? MDN says `<input>`, `<textarea>`, `<select>`, and `<form>`
2. `img[decoding]`: missing value default of `'auto'`
3. `[loading]` should be ordered after `[keytype]` and `[kind]`
4. `[formmethod]` should have a `missing` of `null` (from the spec: "The `formmethod` attribute ... has no missing value default."). Maybe also change the comment to update the `[method]`, because it isn't actually 100% synced...
5. `[formenctype]`  should have a `missing` of `null` (from the spec: "The `formenctype` attribute ... has no missing value default."). Maybe also change the comment to update the `[enctype]`, because it isn't actually 100% synced...
5. `[formtarget]`  probably should have a `missing` of `null` (couldn't find it in the spec, but seems consistent with the others). Maybe also change the comment to update the `[target]`, because it isn't actually 100% synced...
6. the missing value default for `li[type]` should be `null`? (from MDN: "This type overrides the one used by its parent <ol> element, if any.")

Would you prefer I opened a new issue for these and the other two issues above?

---

Additionally, I wonder if it would make sense to add additional information to address the caveat you noted in your comment for attributes like `inputMode` (where they only apply to elements with either a) presence of an attribute or b) an attribute set to a certain value):

```js
  inputMode: {
    // In fact only applies to `text`, `search`, and `password`.
    tagNames: 'input',
```

Eg. either changing `tagNames` to `selectors` and allowing a value like `['input[type="text"]', 'input[type="search"]', 'input[type="password"]']`, or adding an additional field like `tagMatcher`, which could allow a more powerful approach like a function (`(el) => /text|search|password/.test(el.type)`). I suppose the law of least power would suggest something closer to the first approach though.

**Comment by karlhorky** [comment]
Ok, opened #38 for the comments above.

**Comment by karlhorky** [comment]
And also #39 for the more complex matching conditions mentioned in [my comment above](https://github.com/rehypejs/rehype-minify/issues/36#issuecomment-749496827).
