### ISSUE TITLE
rehype-minify-whitespace collapses inline javascript wrongly.

### ISSUE THREAD

**Issue by tripodsan** [rehypejs/rehype-minify#44]
### Initial checklist

- [X] I read the [support docs](https://github.com/rehypejs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/rehypejs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/rehypejs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Arehypejs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

rehype-minify-whitespace@5.0.0

### Link to runnable example

https://codesandbox.io/s/eloquent-noether-zkw11y?file=/src/index.js

### Steps to reproduce

create a html with an inline script with:

```html
<script>
// comment
a=1;
</script>
```

and use `rehype-minify-whitespace`

### Expected behavior

the whitespaces in the script tag should be folded correctly.

### Actual behavior

the scripts are collapsed into a single line, but not accounted for line comments.

```
<script>// comment a=1;</script>
```

### Runtime

Node v14

### Package manager

npm 8

### OS

macOS

**Comment by wooorm** [comment]
Nice catch.
The algorithm currently only considers how text is presented on screen (say, when the script had `display:block`): https://github.com/rehypejs/rehype-minify/blob/fb62ec38ae7b22a9f76a9751198109eb0366ff6b/packages/rehype-minify-whitespace/index.js.
But we should probably consider: https://github.com/rehypejs/rehype-minify/blob/fb62ec38ae7b22a9f76a9751198109eb0366ff6b/packages/html-whitespace-sensitive-tag-names/index.js#L28

Is this something you could help with?

**Comment by wooorm** [comment]
released, thanks! https://github.com/rehypejs/rehype-minify/releases/tag/rehype-minify-whitespace%405.0.1
