### ISSUE TITLE
Upgrade @types/hast to 3

### ISSUE THREAD

**Issue by crutchcorn** [rehypejs/rehype-minify#48]
### Initial checklist

- [X] I read the [support docs](https://github.com/rehypejs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/rehypejs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/rehypejs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Arehypejs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Problem

When using these with other newer packages that use Hast 3, we get errors due to typing mismatches.

### Solution

Upgrade @types/hast to 3. However, I'm not sure if this also requires us to migrate runtime packages as well.

### Alternatives

Not alternative, but a volunteer message from me that I'd be happy to work on upgrading deps wherever makes sense in this library. [We](https://github.com/unicorn-utterances/unicorn-utterances) depends on `hast-util-to-string` so anything we can do to help; let us know.

**Comment by wooorm** [comment]
Hey! Everything’s being released. But it takes time to go through 700+ packages.
This is also a types-only change, so you can ts-ignore/ts-expect-error and continue.
You can follow me or occasionally check https://github.com/wooorm to see where it’s currently at.

**Comment by wooorm** [comment]
Done https://github.com/rehypejs/rehype-minify/releases/tag/7.0.0
