### ISSUE TITLE
rehype-minify-whitspace: TypeError: Cannot read properties of undefined (reading 'hidden')

### ISSUE THREAD

**Issue by tripodsan** [rehypejs/rehype-minify#49]
### Initial checklist

- [X] I read the [support docs](https://github.com/rehypejs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/rehypejs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/rehypejs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Arehypejs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

rehype-minify-whitespace@6.0.0

### Steps to reproduce

passing a node w/o `properties` causes an error in:

https://github.com/rehypejs/rehype-minify/blob/main/packages/rehype-minify-whitespace/lib/index.js#L291

### Expected behavior

node w/o properties should be ignored.

### Actual behavior

node w/o properties causes an error.

### Runtime

Node v16

### Package manager

npm 8

### OS

macOS

**Comment by wooorm** [comment]
Hi. This is expected. This is one of the major changes. All elements must have `properties`. Make sure when you have your own code that generates elements, that a `properties` object exists!
